export const applicationData = [
  {
    id: "app-1",
    name: "Marketing Portal",
    description: "Internal marketing campaign management system",
    logo: "/musical-performance.png",
    status: "healthy",
    errorCount: 0,
    lastUpdated: "Today at 10:45 AM",
    category: "Marketing",
    usageCount: 15,
    isExternal: false,
    contactPerson: {
      name: "Jessica Thompson",
      email: "j.thompson@company.com",
      phone: "+1 (555) 123-4567",
    },
    recentIssues: [
      { date: "2023-05-10", count: 2 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 1 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 0 },
    ],
  },
  {
    id: "app-2",
    name: "Customer Dashboard",
    description: "Customer-facing analytics dashboard",
    logo: "/compact-disc.png",
    status: "warning",
    errorCount: 3,
    lastUpdated: "Today at 9:30 AM",
    category: "Customer Service",
    usageCount: 42,
    isExternal: true,
    contactPerson: {
      name: "Michael Chen",
      email: "m.chen@company.com",
      phone: "+1 (555) 987-6543",
    },
    company: {
      name: "DataViz Solutions",
      website: "https://dataviz-solutions.example.com",
      supportEmail: "support@dataviz-solutions.example.com",
      supportPhone: "+1 (800) 555-1234",
    },
    recentIssues: [
      { date: "2023-05-10", count: 1 },
      { date: "2023-05-11", count: 2 },
      { date: "2023-05-12", count: 3 },
      { date: "2023-05-13", count: 1 },
      { date: "2023-05-14", count: 0 },
    ],
  },
  {
    id: "app-3",
    name: "Inventory System",
    description: "Warehouse inventory management",
    logo: "/abstract-geometric-is.png",
    status: "critical",
    errorCount: 7,
    lastUpdated: "Yesterday at 4:15 PM",
    category: "Operations",
    usageCount: 28,
    isExternal: false,
    contactPerson: {
      name: "Robert Johnson",
      email: "r.johnson@company.com",
      phone: "+1 (555) 234-5678",
    },
    recentIssues: [
      { date: "2023-05-10", count: 3 },
      { date: "2023-05-11", count: 2 },
      { date: "2023-05-12", count: 5 },
      { date: "2023-05-13", count: 4 },
      { date: "2023-05-14", count: 7 },
    ],
  },
  {
    id: "app-4",
    name: "HR Portal",
    description: "Employee management system",
    logo: "/hr-team-meeting.png",
    status: "healthy",
    errorCount: 0,
    lastUpdated: "Today at 11:20 AM",
    category: "Human Resources",
    usageCount: 22,
    isExternal: false,
    contactPerson: {
      name: "Sarah Wilson",
      email: "s.wilson@company.com",
      phone: "+1 (555) 345-6789",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 1 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 0 },
    ],
  },
  {
    id: "app-5",
    name: "Finance App",
    description: "Financial reporting and analytics",
    logo: "/abstract-fa.png",
    status: "warning",
    errorCount: 2,
    lastUpdated: "Today at 8:45 AM",
    category: "Finance",
    usageCount: 18,
    isExternal: true,
    contactPerson: {
      name: "David Miller",
      email: "d.miller@company.com",
      phone: "+1 (555) 456-7890",
    },
    company: {
      name: "FinTech Solutions",
      website: "https://fintech-solutions.example.com",
      supportEmail: "support@fintech-solutions.example.com",
      supportPhone: "+1 (800) 555-5678",
    },
    recentIssues: [
      { date: "2023-05-10", count: 1 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 2 },
      { date: "2023-05-13", count: 1 },
      { date: "2023-05-14", count: 2 },
    ],
  },
  {
    id: "app-6",
    name: "Sales CRM",
    description: "Customer relationship management",
    logo: "/stylized-initials-sc.png",
    status: "healthy",
    errorCount: 1,
    lastUpdated: "Yesterday at 5:30 PM",
    category: "Sales",
    usageCount: 35,
    isExternal: true,
    contactPerson: {
      name: "Emma Johnson",
      email: "e.johnson@company.com",
      phone: "+1 (555) 567-8901",
    },
    company: {
      name: "SalesForce Pro",
      website: "https://salesforce-pro.example.com",
      supportEmail: "support@salesforce-pro.example.com",
      supportPhone: "+1 (800) 555-9012",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 1 },
      { date: "2023-05-12", count: 0 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 1 },
    ],
  },
  {
    id: "app-7",
    name: "Email Client",
    description: "Corporate email application",
    logo: "/email-communication.png",
    status: "healthy",
    errorCount: 0,
    lastUpdated: "Today at 12:15 PM",
    category: "Communication",
    usageCount: 120,
    isExternal: true,
    contactPerson: {
      name: "Thomas Wright",
      email: "t.wright@company.com",
      phone: "+1 (555) 678-9012",
    },
    company: {
      name: "CloudMail",
      website: "https://cloudmail.example.com",
      supportEmail: "support@cloudmail.example.com",
      supportPhone: "+1 (800) 555-3456",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 0 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 0 },
    ],
  },
  {
    id: "app-8",
    name: "Chat App",
    description: "Internal messaging platform",
    logo: "/stylized-chat-bubbles.png",
    status: "healthy",
    errorCount: 0,
    lastUpdated: "Today at 1:30 PM",
    category: "Communication",
    usageCount: 95,
    isExternal: false,
    contactPerson: {
      name: "Olivia Martinez",
      email: "o.martinez@company.com",
      phone: "+1 (555) 789-0123",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 0 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 0 },
    ],
  },
  {
    id: "app-9",
    name: "Video Conferencing",
    description: "Virtual meeting solution",
    logo: "/video-conference.png",
    status: "warning",
    errorCount: 1,
    lastUpdated: "Yesterday at 3:45 PM",
    category: "Communication",
    usageCount: 78,
    isExternal: true,
    contactPerson: {
      name: "William Davis",
      email: "w.davis@company.com",
      phone: "+1 (555) 890-1234",
    },
    company: {
      name: "MeetNow",
      website: "https://meetnow.example.com",
      supportEmail: "support@meetnow.example.com",
      supportPhone: "+1 (800) 555-7890",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 1 },
      { date: "2023-05-12", count: 0 },
      { date: "2023-05-13", count: 1 },
      { date: "2023-05-14", count: 1 },
    ],
  },
  {
    id: "app-10",
    name: "Document Editor",
    description: "Collaborative document editing",
    logo: "/document-stack.png",
    status: "healthy",
    errorCount: 0,
    lastUpdated: "Today at 9:20 AM",
    category: "Productivity",
    usageCount: 110,
    isExternal: true,
    contactPerson: {
      name: "Sophia Brown",
      email: "s.brown@company.com",
      phone: "+1 (555) 901-2345",
    },
    company: {
      name: "DocCollab",
      website: "https://doccollab.example.com",
      supportEmail: "support@doccollab.example.com",
      supportPhone: "+1 (800) 555-2345",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 0 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 0 },
    ],
  },
  {
    id: "app-11",
    name: "Spreadsheet Tool",
    description: "Data analysis and reporting",
    logo: "/spreadsheet-data.png",
    status: "healthy",
    errorCount: 0,
    lastUpdated: "Today at 10:10 AM",
    category: "Productivity",
    usageCount: 85,
    isExternal: true,
    contactPerson: {
      name: "James Wilson",
      email: "j.wilson@company.com",
      phone: "+1 (555) 012-3456",
    },
    company: {
      name: "DataSheet Pro",
      website: "https://datasheet-pro.example.com",
      supportEmail: "support@datasheet-pro.example.com",
      supportPhone: "+1 (800) 555-4567",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 0 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 0 },
    ],
  },
  {
    id: "app-12",
    name: "Presentation Maker",
    description: "Slide creation and presentation tool",
    logo: "/dynamic-presentation.png",
    status: "healthy",
    errorCount: 0,
    lastUpdated: "Yesterday at 2:15 PM",
    category: "Productivity",
    usageCount: 65,
    isExternal: true,
    contactPerson: {
      name: "Isabella Garcia",
      email: "i.garcia@company.com",
      phone: "+1 (555) 123-4567",
    },
    company: {
      name: "SlideMaster",
      website: "https://slidemaster.example.com",
      supportEmail: "support@slidemaster.example.com",
      supportPhone: "+1 (800) 555-6789",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 0 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 0 },
    ],
  },
  {
    id: "app-13",
    name: "Project Management",
    description: "Task and project tracking",
    logo: "/project-management-teamwork.png",
    status: "warning",
    errorCount: 2,
    lastUpdated: "Today at 8:30 AM",
    category: "Productivity",
    usageCount: 72,
    isExternal: false,
    contactPerson: {
      name: "Ethan Martinez",
      email: "e.martinez@company.com",
      phone: "+1 (555) 234-5678",
    },
    recentIssues: [
      { date: "2023-05-10", count: 1 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 2 },
      { date: "2023-05-13", count: 1 },
      { date: "2023-05-14", count: 2 },
    ],
  },
  {
    id: "app-14",
    name: "Security Scanner",
    description: "Vulnerability assessment tool",
    logo: "/digital-security-abstract.png",
    status: "healthy",
    errorCount: 0,
    lastUpdated: "Today at 11:45 AM",
    category: "Security",
    usageCount: 15,
    isExternal: true,
    contactPerson: {
      name: "Alexander Lee",
      email: "a.lee@company.com",
      phone: "+1 (555) 345-6789",
    },
    company: {
      name: "SecureShield",
      website: "https://secureshield.example.com",
      supportEmail: "support@secureshield.example.com",
      supportPhone: "+1 (800) 555-8901",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 0 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 0 },
    ],
  },
  {
    id: "app-15",
    name: "Antivirus Solution",
    description: "Malware protection system",
    logo: "/antivirus-software.png",
    status: "healthy",
    errorCount: 0,
    lastUpdated: "Today at 9:50 AM",
    category: "Security",
    usageCount: 130,
    isExternal: true,
    contactPerson: {
      name: "Mia Johnson",
      email: "m.johnson@company.com",
      phone: "+1 (555) 456-7890",
    },
    company: {
      name: "VirusGuard",
      website: "https://virusguard.example.com",
      supportEmail: "support@virusguard.example.com",
      supportPhone: "+1 (800) 555-0123",
    },
    recentIssues: [
      { date: "2023-05-10", count: 0 },
      { date: "2023-05-11", count: 0 },
      { date: "2023-05-12", count: 0 },
      { date: "2023-05-13", count: 0 },
      { date: "2023-05-14", count: 0 },
    ],
  },
]
